package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Amigos_ventana extends AbsoluteLayout {
	protected VerticalLayout datosPerfil;
	protected Image imagenPerfil;
	protected Label nickUsuario;
	protected Label descripcionUsuario;
	protected Button volverAtras;
	protected Label tituloMensajesdeUsuario;
	protected Grid listaMensajes;
	protected HorizontalLayout cajaAmigos;
	protected Image imagenUsuario;
	protected Label nombreUsuario;
	protected HorizontalLayout cajaAmigos1;
	protected Image imagenUsuario1;
	protected Label nombreUsuario1;
	protected HorizontalLayout cajaAmigos2;
	protected Image imagenUsuario2;
	protected Label nombreUsuario2;
	protected HorizontalLayout cajaAmigos3;
	protected Image imagenUsuario3;
	protected Label nombreUsuario3;
	protected HorizontalLayout cajaAmigos4;
	protected Image imagenUsuario4;
	protected Label nombreUsuario4;
	protected HorizontalLayout cajaAmigos5;
	protected Image imagenUsuario5;
	protected Label nombreUsuario5;

	public Amigos_ventana() {
		Design.read(this);
	}
}
