package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.declarative.Design;
import com.vaadin.v7.ui.VerticalLayout;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Panel_de_control_ventana extends AbsoluteLayout {
	protected Label tituloMensajesdeUsuario;
	protected VerticalLayout controlMensajes;
	protected HorizontalLayout cajaMensaje;
	protected Image imagenTema;
	protected Label mensaje;
	protected Label temaMensaje;
	protected Label fechaMensajeUsuario;
	protected Link eliminarMensaje14;
	protected HorizontalLayout cajaMensaje1;
	protected Image imagenTema1;
	protected Label mensaje1;
	protected Label temaMensaje1;
	protected Label fechaMensajeUsuario1;
	protected Link eliminarMensaje13;
	protected HorizontalLayout cajaMensaje11;
	protected Image imagenTema11;
	protected Label mensaje11;
	protected Label temaMensaje11;
	protected Label fechaMensajeUsuario11;
	protected Link eliminarMensaje12;
	protected HorizontalLayout cajaMensaje12;
	protected Image imagenTema12;
	protected Label mensaje12;
	protected Label temaMensaje12;
	protected Label fechaMensajeUsuario12;
	protected Link eliminarMensaje11;
	protected HorizontalLayout cajaMensaje13;
	protected Image imagenTema13;
	protected Label mensaje13;
	protected Label temaMensaje13;
	protected Label fechaMensajeUsuario13;
	protected Link eliminarMensaje1;
	protected HorizontalLayout cajaMensaje15;
	protected Image imagenTema15;
	protected Label mensaje15;
	protected Label temaMensaje15;
	protected Label fechaMensajeUsuario15;
	protected Link eliminarMensaje;
	protected Label tituloModeradores;
	protected VerticalLayout paneldeControl;
	protected Button moderadores;
	protected Button temaOculto;
	protected Button mensajeOculto;
	protected Button usuarioNotificado;
	protected Button tickets;
	protected Button gestionPublicidad;
	protected Label tituloTemas;
	protected Label tituloMensajes;
	protected Label tituloUsuariosNotificados;
	protected VerticalLayout controlModeradores;
	protected HorizontalLayout cajaModerador;
	protected Image imagenTema2;
	protected Label nombreUsuario;
	protected Link eliminarMensaje141;
	protected HorizontalLayout cajaModerador1;
	protected Image imagenTema21;
	protected Label nombreUsuario1;
	protected Link eliminarMensaje1411;
	protected VerticalLayout controlTemasOcultos;
	protected HorizontalLayout cajaMensaje3;
	protected Image imagenTema3;
	protected Label temaMensaje3;
	protected Label fechaMensajeUsuario3;
	protected Link eliminarMensaje142;
	protected HorizontalLayout cajaMensaje16;
	protected Image imagenTema16;
	protected Label temaMensaje16;
	protected Label fechaMensajeUsuario16;
	protected Link eliminarMensaje132;
	protected HorizontalLayout cajaMensaje112;
	protected Image imagenTema112;
	protected Label temaMensaje112;
	protected Label fechaMensajeUsuario112;
	protected Link eliminarMensaje122;
	protected HorizontalLayout cajaMensaje122;
	protected Image imagenTema122;
	protected Label temaMensaje122;
	protected Label fechaMensajeUsuario122;
	protected Link eliminarMensaje112;
	protected HorizontalLayout cajaMensaje132;
	protected Image imagenTema132;
	protected Label temaMensaje132;
	protected Label fechaMensajeUsuario132;
	protected Link eliminarMensaje16;
	protected HorizontalLayout cajaMensaje152;
	protected Image imagenTema152;
	protected Label temaMensaje152;
	protected Label fechaMensajeUsuario152;
	protected Link eliminarMensaje3;
	protected VerticalLayout controlNotificados;
	protected HorizontalLayout cajaNotificado;
	protected Image imagenUsuario;
	protected Label nombreUsuario2;
	protected Label motivo;
	protected Link banearUsuario;
	protected HorizontalLayout cajaNotificado1;
	protected Image imagenUsuario1;
	protected Label nombreUsuario21;
	protected Label motivo1;
	protected Link banearUsuario1;
	protected HorizontalLayout cajaNotificado2;
	protected Image imagenUsuario2;
	protected Label nombreUsuario22;
	protected Label motivo2;
	protected Link banearUsuario2;

	public Panel_de_control_ventana() {
		Design.read(this);
	}
}
