package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Seccion_Ventana extends AbsoluteLayout {
	protected HorizontalLayout cajaMensaje2;
	protected Image imagenTema2;
	protected Label mensaje2;
	protected Label fechaMensajeUsuario2;
	protected Label temaMensaje2;
	protected HorizontalLayout cajaMensaje12;
	protected Image imagenTema12;
	protected Label mensaje12;
	protected Label fechaMensajeUsuario12;
	protected Label temaMensaje12;
	protected HorizontalLayout cajaMensaje111;
	protected Image imagenTema111;
	protected Label mensaje111;
	protected Label fechaMensajeUsuario111;
	protected Label temaMensaje111;
	protected HorizontalLayout cajaMensaje21;
	protected Image imagenTema21;
	protected Label mensaje21;
	protected Label fechaMensajeUsuario21;
	protected Label temaMensaje21;
	protected HorizontalLayout cajaMensaje121;
	protected Image imagenTema121;
	protected Label mensaje121;
	protected Label fechaMensajeUsuario121;
	protected Label temaMensaje121;
	protected HorizontalLayout cajaMensaje22;
	protected Image imagenTema22;
	protected Label mensaje22;
	protected Label fechaMensajeUsuario22;
	protected Label temaMensaje22;
	protected HorizontalLayout cajaMensaje122;
	protected Image imagenTema122;
	protected Label mensaje122;
	protected Label fechaMensajeUsuario122;
	protected Label temaMensaje122;
	protected HorizontalLayout cajaMensaje1111;
	protected Image imagenTema1111;
	protected Label mensaje1111;
	protected Label fechaMensajeUsuario1111;
	protected Label temaMensaje1111;
	protected HorizontalLayout cajaMensaje23;
	protected Image imagenTema23;
	protected Label mensaje23;
	protected Label fechaMensajeUsuario23;
	protected Label temaMensaje23;
	protected HorizontalLayout cajaMensaje1112;
	protected Image imagenTema1112;
	protected Label mensaje1112;
	protected Label fechaMensajeUsuario1112;
	protected Label temaMensaje1112;
	protected HorizontalLayout cajaMensaje124;
	protected Image imagenTema124;
	protected Label mensaje124;
	protected Label fechaMensajeUsuario124;
	protected Label temaMensaje124;
	protected HorizontalLayout cajaMensaje24;
	protected Image imagenTema24;
	protected Label mensaje24;
	protected Label fechaMensajeUsuario24;
	protected Label temaMensaje24;
	protected HorizontalLayout cajaMensaje123;
	protected Image imagenTema123;
	protected Label mensaje123;
	protected Label fechaMensajeUsuario123;
	protected Label temaMensaje123;
	protected HorizontalLayout cajaMensaje;
	protected Image imagenTema;
	protected Label mensaje;
	protected Label fechaMensajeUsuario;
	protected Label temaMensaje;
	protected HorizontalLayout cajaMensaje1;
	protected Image imagenTema1;
	protected Label mensaje1;
	protected Label fechaMensajeUsuario1;
	protected Label temaMensaje1;
	protected HorizontalLayout cajaMensaje11;
	protected Image imagenTema11;
	protected Label mensaje11;
	protected Label fechaMensajeUsuario11;
	protected Label temaMensaje11;
	protected HorizontalLayout cajaMensaje3;
	protected Image imagenTema3;
	protected Label mensaje3;
	protected HorizontalLayout cajaMensaje13;
	protected Image imagenTema13;
	protected Label mensaje13;
	protected HorizontalLayout cajaMensaje112;
	protected Image imagenTema112;
	protected Label mensaje112;
	protected HorizontalLayout cajaMensaje131;
	protected Image imagenTema131;
	protected Label mensaje131;
	protected HorizontalLayout cajaMensaje132;
	protected Image imagenTema132;
	protected Label mensaje132;
	protected HorizontalLayout cajaMensaje133;
	protected Image imagenTema133;
	protected Label mensaje133;

	public Seccion_Ventana() {
		Design.read(this);
	}
}
