package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Visualizar_seccion_Ventana extends AbsoluteLayout {
	protected HorizontalLayout cajaMensaje2;
	protected Image imagenTema2;
	protected Label mensaje2;
	protected Label fechaMensajeUsuario2;
	protected Label temaMensaje2;
	protected Label temaMensaje25;
	protected HorizontalLayout cajaMensaje21;
	protected Image imagenTema21;
	protected Label mensaje21;
	protected Label fechaMensajeUsuario21;
	protected Label temaMensaje21;
	protected Label temaMensaje251;
	protected HorizontalLayout cajaMensaje22;
	protected Image imagenTema22;
	protected Label mensaje22;
	protected Label fechaMensajeUsuario22;
	protected Label temaMensaje22;
	protected Label temaMensaje252;
	protected HorizontalLayout cajaMensaje23;
	protected Image imagenTema23;
	protected Label mensaje23;
	protected Label fechaMensajeUsuario23;
	protected Label temaMensaje23;
	protected Label temaMensaje253;
	protected HorizontalLayout cajaMensaje24;
	protected Image imagenTema24;
	protected Label mensaje24;
	protected Label fechaMensajeUsuario24;
	protected Label temaMensaje24;
	protected Label temaMensaje254;
	protected HorizontalLayout cajaMensaje25;
	protected Image imagenTema25;
	protected Label mensaje26;
	protected Label fechaMensajeUsuario25;
	protected Label temaMensaje26;
	protected Label temaMensaje255;
	protected HorizontalLayout cajaMensaje26;
	protected Image imagenTema26;
	protected Label mensaje27;
	protected Label fechaMensajeUsuario26;
	protected Label temaMensaje27;
	protected Label temaMensaje256;
	protected HorizontalLayout cajaMensaje27;
	protected Image imagenTema27;
	protected Label mensaje28;
	protected Label fechaMensajeUsuario27;
	protected Label temaMensaje28;
	protected Label temaMensaje257;
	protected HorizontalLayout cajaMensaje28;
	protected Image imagenTema28;
	protected Label mensaje29;
	protected Label fechaMensajeUsuario28;
	protected Label temaMensaje29;
	protected Label temaMensaje258;
	protected HorizontalLayout cajaMensaje29;
	protected Image imagenTema29;
	protected Label mensaje210;
	protected Label fechaMensajeUsuario29;
	protected Label temaMensaje210;
	protected Label temaMensaje259;
	protected HorizontalLayout cajaMensaje210;
	protected Image imagenTema210;
	protected Label mensaje211;
	protected Label fechaMensajeUsuario210;
	protected Label temaMensaje211;
	protected Label temaMensaje2510;
	protected HorizontalLayout cajaMensaje211;
	protected Image imagenTema211;
	protected Label mensaje212;
	protected Label fechaMensajeUsuario211;
	protected Label temaMensaje212;
	protected Label temaMensaje2511;
	protected HorizontalLayout cajaMensaje212;
	protected Image imagenTema212;
	protected Label mensaje213;
	protected Label fechaMensajeUsuario212;
	protected Label temaMensaje213;
	protected Label temaMensaje2512;
	protected HorizontalLayout cajaMensaje3;
	protected Image imagenTema3;
	protected Label mensaje3;
	protected HorizontalLayout cajaMensaje13;
	protected Image imagenTema13;
	protected Label mensaje13;
	protected HorizontalLayout cajaMensaje112;
	protected Image imagenTema112;
	protected Label mensaje112;
	protected HorizontalLayout cajaMensaje131;
	protected Image imagenTema131;
	protected Label mensaje131;
	protected HorizontalLayout cajaMensaje132;
	protected Image imagenTema132;
	protected Label mensaje132;
	protected HorizontalLayout cajaMensaje133;
	protected Image imagenTema133;
	protected Label mensaje133;
	protected Label mensaje25;

	public Visualizar_seccion_Ventana() {
		Design.read(this);
	}
}
